### ISSUE TITLE
Please add these links to the GFX wiki

### ISSUE THREAD

**Issue by swhcz** [JayFoxRox/Pro-Pinball-Super-Ultra#29]
I've just downloaded these vor vertical resolution of 1440:

http://download.pro-pinball.com/ultra/gfx/timeshock/high_no_backbox/1440_1440_4096.zip
http://download.pro-pinball.com/ultra/gfx/timeshock/low/1440_1440_4096.zip
http://download.pro-pinball.com/ultra/gfx/timeshock/medium/1440_1440_4096.zip
http://download.pro-pinball.com/ultra/gfx/timeshock/medium_with_backbox/1440_1708_4096.zip

All work, and can be added to the wiki page.

Question: is there any description/readme available on how to actually install these packs?

**Comment by swhcz** [comment]
Here's more for 1080:

http://download.pro-pinball.com/ultra/gfx/timeshock/high_no_backbox/1080_1080_2048.zip
http://download.pro-pinball.com/ultra/gfx/timeshock/low/1080_1080_2048.zip
http://download.pro-pinball.com/ultra/gfx/timeshock/medium/1080_1080_2048.zip
http://download.pro-pinball.com/ultra/gfx/timeshock/medium_with_backbox/1080_1282_4096.zip

**Comment by swhcz** [comment]
As for the installation, maybe you could add these steps to the Wiki?

----

# Installation

1. download for your vertical resolution
2. go to (game install folder)/extra_data/timeshock
3. go to folder named after your view
4. create sub-folder, named exactly like your zip file (e.g. "1440_1440_4096")
5. extract correct zip here
6. create a file just named "installed", with 0 bytes

Make sure to restart Pro Pinball before attempting to use the just installed pack.

**Comment by JayFoxRox** [comment]
The wiki should be editable by all GitHub users?
**Edit**: This was misconfigured; it's editable now.

I'll see if these links need to be added to archive.org though
**Edit**: Done.

**Edit**: Great regarding installation! My plan was to modify the game to download from archive.org instead (once these URLs break).

**Comment by swhcz** [comment]
Worked now, I've added my text to the wiki.
Many thanks!!
